# version: "3.8"
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    volumes:
      - ./postgress:/var/lib/postgresql/data